# Properties about the file like its creator
fileProperties:
  creatorName: Group3

# Package Info
# Name and description will be displayed in the user interface
packageName: Sherlock Squad and the Haunted Castle Mod
packageDescription: Group 3 mod
packageVersion: "0.1.0"

maxSaveSlots: 1
# Levels
# All of the levels contained within this package
# Each level has the following properties:
#   - levelId: Unique id for the level
#   - levelName: The name that will displayed in the user interface
#   - unlockedByDefault: If true, the level will be playable from the start
#                          If false, the previous level will have to be completed first
#   - minCuresToProgress: The minimum number of patients that must be cured to
#                           complete the level and progress to the next one
#   - levelCutscene: Name (if any) of the cutscene to be played
#   - levelFiles: List of yaml files that define this level
#       -- playerCount: If this many people are playing, the level file will be used
#       -- fileName: Name of the yaml file to be loaded

levels:

  - levelId: level1
    levelName: level1
    unlockedByDefault: true
    minCuresToProgress: 0
    levelCutscene: "" # not yet used
    levelFiles:
      - { playerCount: 2, fileName: "Level_esther_2_players" }
      - { playerCount: 3, fileName: "Level_esther_3_players" }
      - { playerCount: 4, fileName: "Level_esther_4_players" }


  - levelId: level2
    levelName: level2
    unlockedByDefault: true
    minCuresToProgress: 0
    levelCutscene: "" # not yet used
    levelFiles:
      - { playerCount: 2, fileName: "Level_george_2_players" }
      - { playerCount: 3, fileName: "Level_george_3_players" }
      - { playerCount: 4, fileName: "Level_george_4_players" }

  - levelId: level3
    levelName: level3
    unlockedByDefault: true
    minCuresToProgress: 0
    levelCutscene: "" # not yet used
    levelFiles:
      - { playerCount: 2, fileName: "Level_main_demo_2_players" }
      - { playerCount: 3, fileName: "Level_main_demo_3_players" }
      - { playerCount: 4, fileName: "Level_main_demo_4_players" }

  - levelId: level4
    levelName: level4
    unlockedByDefault: true
    minCuresToProgress: 0
    levelCutscene: "" # not yet used
    levelFiles:
      - { playerCount: 2, fileName: "Level_megan_2_players" }
      - { playerCount: 3, fileName: "Level_megan_3_players" }
      - { playerCount: 4, fileName: "Level_megan_4_players" }


  - levelId: level5
    levelName: level5
    unlockedByDefault: true
    minCuresToProgress: 0
    levelCutscene: "" # not yet used
    levelFiles:
      - { playerCount: 2, fileName: "Level_mo_2_players" }
      - { playerCount: 3, fileName: "Level_mo_3_players" }
      - { playerCount: 4, fileName: "Level_mo_4_players" }

